### ISSUE TITLE
Add option to allow overwrites

### ISSUE THREAD

**Issue by jacobwegner** [eldarion/django-gapc-storage#4]
Add an option or additional storage backend that allows overwrites.

This is especially useful if the storage backend is being used to update existing objects (similar to what you might do on a local file system opening and writing to an existing file).

Roughly:

```
    def get_available_name(self, name):
        """
        Always assume a name is available.
        """
        return name
```

**Comment by jacobwegner** [comment]
@brosner: Should this also be configurable via a `GAPC_STORAGE` key (`allow_overwrite`)?

**Comment by brosner** [comment]
Let's get this in the next release.
