### ISSUE TITLE
Add option to specify cache headers

### ISSUE THREAD

**Issue by jacobwegner** [eldarion/django-gapc-storage#5]
By default, GCS caches any [publicly accessible objects for 3600 seconds](https://cloud.google.com/storage/docs/static-website#tip-cache).

Especially if a developer is trying to update an existing object (see #4), it may not be desirable to have objects with that long of a cache value.

Either add an option to `GoogleCloudStorage` to specify cache headers or an additional backend that supports custom cache headers.

```

GCS_PUBLIC_READ_CACHE_DEFAULT = "public, max-age=3600"

...

class CustomCacheMediaStorage(GoogleCloudStorage):
    """
    Custom subclass of GoogleCloudStorage that allows customization of GCS's
    cache-control header
    """
    cache_control = GCS_PUBLIC_READ_CACHE_DEFAULT

    def _save(self, name, content):
        mimetype, _ = mimetypes.guess_type(os.path.basename(name))
        if mimetype is None:
            mimetype = "application/octet-stream"
        media = MediaIoBaseUpload(content, mimetype)
        req = self.client.objects().insert(
            bucket=self.bucket,
            name=self._prefixed_name(name),
            body={
                "cacheControl": self.cache_control
            },
            media_body=media
        )
        req.execute()
        return name

...

class NoCacheMediaStorage(CustomCacheMediaStorage):
    # never cache
    cache_control = "private, max-age=0"

```

**Comment by jacobwegner** [comment]
@brosner any thoughts about how we want to implement this?  Perhaps add a `GAPC_STORAGE` key for `cacheControl`?

**Comment by jacobwegner** [comment]
@brosner: would like to revisit your thoughts on this and #4 for the next release

**Comment by brosner** [comment]
I am in favor of adding a setting to control this behavior. `cache_control` key in `GAPC_STORAGE` sounds right to me.
